### ISSUE TITLE
Colshape.isEntityIn returns true, when entity is not inside the colshape

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2092]
### Description of the problem

I've noticed that Colshape.isEntityIn has been returning incorrect boolean sometimes. So I created a custom method to double check the calculations and print a warning when the original Colshape.isEntityIn calculation is incorrect. Since then I've received 55k warnings.

Custom method on server-side. It only prints a warning if isEntityIn method returns true, but it should really return false:
```ts
alt.Colshape.prototype.isEntityInEx = function (this: alt.Colshape, entity: alt.Entity): boolean {
    if(!this.valid || entity === null || !entity.valid) 
        return false;

    if(this.playersOnly && !(entity instanceof alt.Player)) 
        return false;

    if(this.dimension !== entity.dimension) 
        return false;

    if(!this.isEntityIn(entity)) 
        return false;

    // Check if entity is inside the colshape (use 2d vector if colshape is 2d)
    // We only ever use ColshapeSphere and ColshapeCircle, so this is enough.
    const entityPos = this.pos.z === 0 ? new alt.Vector3(entity.pos.x, entity.pos.y, 0) : entity.pos;

    // Double check to make sure if entity is truly inside the colshape
    const distanceToColshape = entityPos.distanceTo(this.pos);
    if(distanceToColshape > this.radius) { 

        alt.logWarning(
            `[Colshape.isEntityInEx] Entity ${ entity.getTypeString() }{ id: ${ entity.id } } is inside colshape ${ this.getTypeString() }{ id: ${ this.id }, name: ${ this.name } } but distance is greater than radius.`, 
            { 
                colshape: {
                    dimension: this.dimension, 
                    pos: this.pos, 
                    radius: this.radius, 
                    colshapeType: this.colshapeType,
                }, 
                entity: {
                    dimension: entity.dimension, 
                    pos: entity.pos,
                }, 
                distanceToColshape: distanceToColshape,
                isPointIn: this.isPointIn(entityPos),
            }
        );

        return false;
    }

    return true;
}
```

For example one of the 55k logs I've received:
```js
[13:25:06][Warning] [Colshape.isEntityInEx] Entity Player{ id: 32 } is inside colshape Colshape{ id: 4, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: 148.4703369140625,
      y: 6622.18017578125,
      z: 31.773681640625
    },
    radius: 60,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: -452.75604248046875,
      y: -361.26593017578125,
      z: 33.7281494140625
    }
  },
  distanceToColshape: 7009.2793134551675,
  isPointIn: false
}
```

At the same time isPointIn method seems to return false (the correct value), but isEntityIn method returns true.

### Reproduction steps

I could not reproduce the issue by myself on the test server, but it's been happening often on the production server. It seems to only return an incorrect value when certain conditions are met, which I had not been able to figure out yet, but this is the code I've used.

1) Create colshape `const colshape = new alt.ColshapeSphere(pos.x, pos.y, pos.z, radius);`.
2) With timer print results of colshape.isEntityIn(player).
3) Move about and see if logs incorrect values.

```ts
new alt.ColshapeSphere(148.4703369140625, 6622.18017578125, 31.773681640625, 60);
new alt.ColshapeSphere(-244.5230712890625, 6209.103515625, 37.182373046875, 50);

alt.setInterval(() => {

    const players = alt.Player.all;
    const colshapes = alt.Colshape.all;

    players.forEach(player => {
        if(!player.valid) return;

        colshapes.forEach(colshape => {
            const isPlayerInColshape = colshape.isEntityIn(player);
            const isPlayerInColshapeEx = colshape.isEntityInEx(player);
            const isPointIn = colshape.isPointIn(player.pos);

            if(isPlayerInColshape !== isPlayerInColshapeEx) {
                alt.logWarning(`Colsphape.isEntityInEx is not equal to Colshape.isEntityIn. colshape: ${ colshape.id }, isEntityIn: ${ isPlayerInColshape }, isEntityInEx: ${ isPlayerInColshapeEx }, isPointIn: ${ isPointIn }`);
            }
        });
    });

}, 1000);

alt.Colshape.prototype.isEntityInEx = function (this: alt.Colshape, entity: alt.Entity): boolean {
    if(!this.valid || entity === null || !entity.valid) 
        return false;

    if(this.playersOnly && !(entity instanceof alt.Player)) 
        return false;

    if(this.dimension !== entity.dimension) 
        return false;

    if(!this.isEntityIn(entity)) 
        return false;

    // Check if entity is inside the colshape (use 2d vector if colshape is 2d)
    // We only ever use ColshapeSphere and ColshapeCircle, so this is enough.
    const entityPos = this.pos.z === 0 ? new alt.Vector3(entity.pos.x, entity.pos.y, 0) : entity.pos;

    // Double check to make sure if entity is truly inside the colshape
    const distanceToColshape = entityPos.distanceTo(this.pos);
    if(distanceToColshape > this.radius) { 

        alt.logWarning(
            `[Colshape.isEntityInEx] Entity ${ entity.getTypeString() }{ id: ${ entity.id } } is inside colshape ${ this.getTypeString() }{ id: ${ this.id }, name: ${ this.name } } but distance is greater than radius.`, 
            { 
                colshape: {
                    dimension: this.dimension, 
                    pos: this.pos, 
                    radius: this.radius, 
                    colshapeType: this.colshapeType,
                }, 
                entity: {
                    dimension: entity.dimension, 
                    pos: entity.pos,
                }, 
                distanceToColshape: distanceToColshape,
                isPointIn: this.isPointIn(entityPos),
            }
        );

        return false;
    }

    return true;
}
```

I've noticed it often happens to players who have their first spawn at the location of the colshape. And after they leave that colshape logs show that they are inside another colshape which is nowhere near them.

### Expected behaviour

Colshape.isEntityIn should return the correct value

### Operating system

Debian 11

### Version

15.27

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
have you checked if its true a second later? entering can take a few mondred milliseconds.

**Comment by FabianTerhorst** [comment]
also did the event fire a second later the colshape event?

**Comment by edgarasx** [comment]
> have you checked if its true a second later? entering can take a few hundred milliseconds.

We run the custom method on leave colshape event and on an interval for all players. It seems once isEntityIn returns an incorrect value it continues to return that same value for that specific colshape and player until player reconnects.

**Comment by edgarasx** [comment]
I've looked through the logs for more information, we have a 5 sec. interval that runs isEntityInEx for every player and here are isEntityInEx logs for a specific player from first spawn to disconnect. It does eventually return the right value:

```js

[14:12:41] ON_PLAYER_SPAWN(player.id: 21)

[14:12:56][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 189.91648864746094,
      y: 2800.3515625,
      z: 45.6241455078125
    }
  },
  distanceToColshape: 3436.3350931906543,
  isPointIn: false
}

[14:13:01][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 188.3208770751953,
      y: 2787.164794921875,
      z: 45.5736083984375
    }
  },
  distanceToColshape: 3449.215694141731,
  isPointIn: false
}

[14:13:06][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 202.7868194580078,
      y: 2800.3515625,
      z: 46.5677490234375
    }
  },
  distanceToColshape: 3437.9883800815674,
  isPointIn: false
}

[14:13:11][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 198.94944763183594,
      y: 2794.655029296875,
      z: 46.5677490234375
    }
  },
  distanceToColshape: 3443.14019843931,
  isPointIn: false
}

[14:13:16][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 198.94944763183594,
      y: 2794.655029296875,
      z: 46.5677490234375
    }
  },
  distanceToColshape: 3443.14019843931,
  isPointIn: false
}

[14:13:21][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 198.94944763183594,
      y: 2794.655029296875,
      z: 46.5677490234375
    }
  },
  distanceToColshape: 3443.14019843931,
  isPointIn: false
}

[14:13:26][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 195.54725646972656,
      y: 2797.96484375,
      z: 46.5509033203125
    }
  },
  distanceToColshape: 3439.4209834642734,
  isPointIn: false
}

[14:13:30][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: 192.3296661376953,
      y: 2845.476806640625,
      z: 45.5062255859375
    }
  },
  distanceToColshape: 3391.886530842593,
  isPointIn: false
}

[14:19:59][Warning] [Colshape.isEntityInEx] Entity Player{ id: 21 } is inside colshape Colshape{ id: 5, name: SafeZone } but distance is greater than radius. {
  colshape: {
    dimension: 0,
    pos: Vector3 {
      x: -244.5230712890625,
      y: 6209.103515625,
      z: 37.182373046875
    },
    radius: 50,
    colshapeType: 0
  },
  entity: {
    dimension: 0,
    pos: Vector3 {
      x: -87.4021987915039,
      y: 6298.140625,
      z: 32.177978515625
    }
  },
  distanceToColshape: 180.6643832770427,
  isPointIn: false
}

[17:03:52] playerDisconnect(playerid: 21)
```

**Comment by FabianTerhorst** [comment]
we don't cleanup id's yet for removed or disconnected entities. maybe id is reused and then it stays true. Can you test that?

**Comment by edgarasx** [comment]
> we don't cleanup id's yet for removed or disconnected entities. maybe id is reused and then it stays true. Can you test that?

It wouldn't make sense, because our safe zone colshapes are never removed and we're sending a valid, connected player to isEntityInEx method.

**Comment by FabianTerhorst** [comment]
> > we don't cleanup id's yet for removed or disconnected entities. maybe id is reused and then it stays true. Can you test that?
> 
> It wouldn't make sense, because our safe zone colshapes are never removed and we're sending a valid, connected player to isEntityInEx method.

I mean that its still true when a player from safezone disconnects and a new one gets the id from the player.

**Comment by edgarasx** [comment]
Good point, I will test that and let you know

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.

**Comment by TuK4z** [comment]
We are having same issue in c#. I also check IsEntityIn and all the conditions described by Edgaras is exact for us. If player dies or reconnects only then player is not in colshape. Could it be that this issue came back? Im using latest release, but issue exists at least for several weeks.
