### ISSUE TITLE
Player in cover is invisible

### ISSUE THREAD

**Issue by KWMSources** [altmp/altv-issues#300]
Player who are in cover (Q) are invisible to other players. If the player in cover shoots, he is also invisible to other players. By this way, the player in cover can shoot to other players without beeing spooted.

## Expected Behavior
The player in cover and the player shooting out of cover is visible to other players (sync).

## Current Behavior
https://www.youtube.com/watch?v=zM-jHtfU-tA&feature=youtu.be

**Comment by Zerefdev** [comment]
some screenshots about the same issue
![20200416001006_1](https://user-images.githubusercontent.com/25670700/79394404-aee06a00-7f77-11ea-89cd-5515e936643a.jpg)

![20200416001010_1](https://user-images.githubusercontent.com/25670700/79394406-b0119700-7f77-11ea-8208-a543edd41fc0.jpg)

**Comment by martonp96** [comment]
The latest dev build (dev/2.1-dev7) should fix this issue, please try it and provide feedback if you can.

**Comment by Heryshaf** [comment]
Works perfectly as i have tested.

**Comment by martonp96** [comment]
Thank you for the feedback.

**Comment by tastydev** [comment]
We tested it after the merge (dev -> rc) and it is still not fixed on rc2.1-rc1. Same behaviour like the above pictures.

**Comment by C0kkie** [comment]
Hm for us it was fine as we tested with Chaos

**Comment by FabianTerhorst** [comment]
Make Sure to Test on Clean gamemode so No natives are involved.

**Comment by tastydev** [comment]
Talked to chaos previously cause entity rotation issues are still not resolved, too. He said that he was testing this too befor and it worked there. We can´t confirm this. Server files are 100% uptodate, so maybe the merge isn´t complete.

**Comment by C0kkie** [comment]
Tested with tasty again, its fine
