### ISSUE TITLE
Vehicle doors sync problem

### ISSUE THREAD

**Issue by x90nik** [altmp/altv-issues#994]
**Client/server version**
`Build #2.24, branch release`

**Current behavior**
1. Spawn random vehicle like `police`.
2. Detach vehicle door by an accident.
3. Get away from the vehicle and back to it again.
4. The vehicle door returns to the default state.

**Expected behavior**
The vehicle's door must be separate from it.
Note: There is only one player in the server.

**Steps to reproduce**

https://user-images.githubusercontent.com/40915667/124362271-2a940880-dc49-11eb-9184-500fe63a3b7e.mp4

https://user-images.githubusercontent.com/40915667/124364948-363bfb00-dc5a-11eb-8f25-2120c80bd3e3.mp4

**Comment by mrgharabaghi** [comment]
Same problem for server side function `setWheelDetached()`.
```js
let newVehicle = new alt.Vehicle(args[0], ...rotationToDirection(player.pos, player.rot), 0, 0, player.rot.z);
newVehicle.setWheelDetached(0, true);
```
https://user-images.githubusercontent.com/40915667/124463648-6d202700-dda8-11eb-82f8-79adfcd8419c.mp4

**Comment by Arochka** [comment]
I was able to reproduce, but didn't work everytime.

**Comment by FabianTerhorst** [comment]
> Same problem for server side function `setWheelDetached()`.
> 
> ```js
> let newVehicle = new alt.Vehicle(args[0], ...rotationToDirection(player.pos, player.rot), 0, 0, player.rot.z);
> newVehicle.setWheelDetached(0, true);
> ```
> 
>  detached.mp4

Wheel stuff got reworked in Dev branch.

**Comment by xxshady** [comment]
fixed in release 6.1

**Comment by xxshady** [comment]
fixed in release 6.1 @mrgharabaghi

**Comment by mrgharabaghi** [comment]
> fixed in release 6.1 @mrgharabaghi

Also for `setWheelDetached()`?

**Comment by xxshady** [comment]
> > fixed in release 6.1 @mrgharabaghi
> 
> Also for `setWheelDetached()`?

yes

**Comment by mrgharabaghi** [comment]
No, I tested a few minutes ago. Detached doors still not sync.
Sometimes sync, and sometimes not.

**Comment by mrgharabaghi** [comment]
And same result for `setWheelDetached()`.
50/50
